@startuml
left to right direction
skinparam packageStyle rectangle

actor 運転手
actor システム

rectangle 入庫システム {
    運転手 -d- (車ナンバー、運転手ナンバーをスキャンする)
    システム -u-> (車ナンバー、運転手ナンバーを確認する)
    運転手 -d-> (駐車スペースに入庫する)
    システム -u-> (入庫を記録する)
}

rectangle 出庫システム {
    運転手 -d-> (駐車スペースから出庫する)
    運転手 -d-> (現金を支払う)
    システム -u-> (金額を算出する)
}

/' ユースケースのソート '/
(車ナンバー、運転手ナンバーをスキャンする) -[hidden]l- (車ナンバー、運転手ナンバーを確認する)
(車ナンバー、運転手ナンバーを確認する) -[hidden]l- (駐車スペースに入庫する)
(駐車スペースに入庫する) -[hidden]l- (入庫を記録する)
(駐車スペースから出庫する) -[hidden]l- (現金を支払う)
(現金を支払う) -[hidden]l- (金額を算出する)

@enduml