@startuml

package 駐車対象 {
  interface 駐車対象参照Repository {
    + 過去駐車経過日数 過去駐車経過日数を取得する(駐車対象情報, システム日付)
  }
  class 駐車対象情報 {
    + static 駐車対象情報 create(車ナンバー, 運転手ナンバー)
  }
  class 車ナンバー {
  }
  class 運転手ナンバー {
  }
  class 過去駐車経過日数 {
    + boolean 駐車して１週間以内か()
  }
  駐車対象参照Repository --> 駐車対象情報
  駐車対象参照Repository --> 過去駐車経過日数
  駐車対象情報 --> 車ナンバー
  駐車対象情報 --> 運転手ナンバー
}
package 入庫 {
  class 入庫情報 {
  }
  class 入庫番号 {
  }
  interface 入庫Repository {
    + 入庫番号 入庫番号を払い出す()
    + void 入庫を記録する(入庫)
  }
  class "入庫\n<Entity>" as 入庫 {
    + static 入庫 create(入庫番号, 入庫情報)
  }
  class 入庫日時 {
  }

  class 入庫判定ポリシー {
    + static 入庫判定 check(入庫情報, 過去駐車経過日数)
  }

  enum 入庫判定 {
    入庫可能
    １週間以内に止めてた
    すでに別の車が入庫済み
    + boolean 入庫可能かどうか()
  }

  入庫 --> 入庫番号
  入庫 --> 入庫情報
  入庫情報 --> 入庫日時

  入庫Repository --> 入庫番号
  入庫Repository --> 入庫

  入庫判定ポリシー --> 入庫情報
  入庫判定ポリシー --> 入庫判定

}

package 出庫 {
  class "出庫\n<Entity>" as 出庫 {
    + static 出庫 create(出庫番号, 出庫情報)
    + 駐車料金 駐車料金を計算する(入庫日時)
  }
  class 出庫番号 {
  }
  class 出庫情報 {
  }
  class 出庫日時 {
  }
  class 出庫判定ポリシー {
    + static 出庫判定 check(出庫情報)
  }
  enum 出庫判定 {
    出庫可能
    その駐車対象情報では停めてない
    + boolean 出庫可能かどうか()
  }
  interface 出庫Repository {
    + 出庫 最後に出庫した情報を参照する(駐車対象情報, 駐車スペース)
    + 出庫番号 出庫番号を払い出す()
    + void 出庫を記録する(出庫)
  }

  出庫 --> 出庫番号
  出庫 --> 出庫情報
  出庫情報 --> 出庫日時
  出庫Repository --> 出庫番号
  出庫Repository --> 出庫
  出庫判定ポリシー --> 出庫情報
  出庫判定ポリシー --> 出庫判定
}

package 駐車スペース管理 {
  class 駐車スペース {
    + 駐車スペース状態 駐車スペース状態を取得する()
  }
  enum 駐車スペース状態 {
    空
    満
  }
  class 駐車スペース番号 {
  }
  interface 駐車スペースRepository {
    + 駐車スペース 駐車スペース情報を取得する(駐車スペース番号)
  }
  enum 料金仕様 {
    500円
    1000円
    + 料金仕様 料金仕様を取得する(平日or土日祝祭日)
  }

  enum 支払方法 {
    現金
  }
  駐車スペースRepository --> 駐車スペース番号
  駐車スペースRepository --> 駐車スペース
  駐車スペース --> 駐車スペース番号
  駐車スペース --> 駐車スペース状態
  駐車スペース --> 料金仕様
}

package 日時 {
  class 日 {
    平日or土日祝祭日 取得する(システム日付)
  }
  class 時間 {
  }
  enum 平日or土日祝祭日 {
    平日
    土日祝祭日
  }

  日 --> システム日付
}

出庫 ----> 駐車料金

入庫情報 --> 支払方法
入庫情報 --> 駐車対象情報
入庫情報 ----> 駐車スペース

入庫判定ポリシー --> 過去駐車経過日数

入庫日時 -----> 日
入庫日時 -----> 時間
出庫日時 -----> 日
出庫日時 -----> 時間

出庫 --> 入庫日時
出庫Repository --> 駐車対象情報
出庫Repository --> 駐車スペース

出庫情報 --> 駐車対象情報
出庫情報 --> 駐車スペース

駐車対象参照Repository --> システム日付

料金仕様 --> 平日or土日祝祭日
日 --> 平日or土日祝祭日


/'
「ちょっと考えるの諦めたところ」
・車とか運転手というドメイン出そうとしたけど、そこまでやるの面倒だったんでナンバーだけ持たせるようにした。
・入庫、出庫を人の手で管理するときは、申請書的なものが必要になるが今回割愛した。出すべき？

「いまだに腑に落ちない点」
・駐車料金のドメインを作り出したが、どこのパッケージにも属さない。ちょっと微妙な気がする
・駐車料金を出すために出庫から入庫日時の線が出てるのおかしい気がする。。
・１週間以内に停めたことがあるかどうかを過去駐車経過日数としてあらわしたが、駐車対象情報に持たせておいてよいものか。。
 '/
@enduml